name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip build-essential ccache zlib1g-dev git openjdk-8-jdk

    - name: Install Buildozer and Cython
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython

    - name: Initialize Buildozer
      run: |
        buildozer init

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: List files
      run: ls -l .  # 列出生成目录中的文件，以确保 APK 存在

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-APK
        path: bin/*.apk  # 使用通配符确保能找到 APK
